# Generated by Django 5.1 on 2024-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="Заголовок сайта (на главной странице)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание сайта ()")),
                ("logo", models.ImageField(upload_to="image/", verbose_name="Логотип")),
                ("banner", models.ImageField(upload_to="image/")),
                ("twitter", models.URLField(verbose_name="Укжите ссылку на twitter")),
                ("facebook", models.URLField(verbose_name="Укжите ссылку на facebook")),
                ("github", models.URLField(verbose_name="Укжите ссылку на github")),
                ("gmail", models.URLField(verbose_name="Укжите ссылку на почту")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки главной страницы",
            },
        ),
    ]
