# Generated by Django 5.1 on 2024-08-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок о нас (о нас)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание о нас ()")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Сеть", "Сеть"),
                            ("Аналитик", "Аналитик"),
                            ("Развитие", "Развитие"),
                        ],
                        max_length=155,
                        verbose_name="иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки о нас",
            },
        ),
    ]
