# Generated by Django 5.1 on 2024-08-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0003_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
