# Generated by Django 5.1 on 2024-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0004_delete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок другое (Другое)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание другое ()")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки другое",
            },
        ),
    ]
