# Generated by Django 5.1 on 2024-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0005_other"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zagolovok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="Заголовок сайта (на главной странице)",
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки заголовка",
            },
        ),
        migrations.RemoveField(
            model_name="index",
            name="title",
        ),
    ]
