# Generated by Django 5.1 on 2024-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0006_zagolovok_remove_index_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="title",
            field=models.CharField(
                default=1,
                max_length=255,
                verbose_name="Заголовок сайта (на главной странице)",
            ),
            preserve_default=False,
        ),
    ]
