# Generated by Django 5.1 on 2024-08-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0008_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "", "verbose_name_plural": "Настройки заголовка"},
        ),
    ]
