# Generated by Django 5.1 on 2024-08-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0010_alter_team_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="foto",
            field=models.ImageField(default=1, upload_to="image/", verbose_name="Фото"),
            preserve_default=False,
        ),
    ]
