# Generated by Django 5.1 on 2024-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0011_team_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Сheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=10, verbose_name="Число в счете (число)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание счета ()")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки счета",
            },
        ),
    ]
