# Generated by Django 5.1 on 2024-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0012_сheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок (сдайд)"),
                ),
                ("description", models.TextField(verbose_name="Описание слайда ()")),
                ("foto1", models.ImageField(upload_to="image/", verbose_name="Фото 1")),
                ("foto2", models.ImageField(upload_to="image/", verbose_name="Фото 2")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки участника",
            },
        ),
    ]
