# Generated by Django 5.1 on 2024-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0013_slaid"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="image/", verbose_name="Фото")),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок ()"),
                ),
                ("description", models.TextField(verbose_name="Описание ()")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки истории",
            },
        ),
        migrations.AlterModelOptions(
            name="slaid",
            options={"verbose_name": "", "verbose_name_plural": "Настройки слайда"},
        ),
    ]
