# Generated by Django 5.1 on 2024-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0014_history_alter_slaid_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок ()"),
                ),
                ("description", models.TextField(verbose_name="Описание ()")),
                ("tip", models.TextField(verbose_name="Описание тип ()")),
                ("date", models.TextField(verbose_name="Описание дата ()")),
                ("slovo", models.TextField(verbose_name="Описание  слово()")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки denga",
            },
        ),
    ]
