# Generated by Django 5.1 on 2024-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geeks", "0015_denga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denga",
            name="date",
            field=models.CharField(max_length=255, verbose_name="Описание дата ()"),
        ),
        migrations.AlterField(
            model_name="denga",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Описание ()"),
        ),
        migrations.AlterField(
            model_name="denga",
            name="slovo",
            field=models.CharField(max_length=255, verbose_name="Описание  слово()"),
        ),
        migrations.AlterField(
            model_name="denga",
            name="tip",
            field=models.CharField(max_length=255, verbose_name="Описание тип ()"),
        ),
    ]
